name: Close Stale Issues & Pull Requests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues/PRs
        uses: actions/stale@v4
        with:
          days-before-stale: 90
          days-before-close: 14
          stale-issue-label: ðŸ’¤ stale
          exempt-issue-labels: ðŸš§ blocked
          stale-issue-message: Marking this issue as stale because it has had no activity in the last 90 days. If there is no new activity in the next 14 days, the issue will be automatically closed.
          stale-pr-label: ðŸ’¤ stale
          exempt-pr-labels: ðŸš§ blocked
          stale-pr-message: Marking this pull request as stale because it has had no activity in the last 90 days. If there is no new activity in the next 14 days, the pull request will be automatically closed.
